### ISSUE TITLE
2.0.0 release?

### ISSUE THREAD

**Issue by J-Swift** [roubachof/NukeProxy#10]
Hey there, looks like the 2.0.0 release never got pushed to the artifact stores? Would you mind pushing that upstream when you get some time? I tried to use a local version of the package but I couldnt figure it out : D

**Comment by roubachof** [comment]
It is released with a different name since now it's targeting .net 6 for MAUI compatibility:

https://www.nuget.org/packages/ImageCaching.Nuke

**Comment by J-Swift** [comment]
Perfect, thanks : )

**Comment by J-Swift** [comment]
@roubachof just a heads up it looks like the package is now 'ImageCaching.Nuke' but the C# namespace is still 'Xamarin.Nuke'. Not sure if that was intended or not.
