### ISSUE TITLE
Bitcode enabled by default

### ISSUE THREAD

**Issue by yurkinh** [roubachof/NukeProxy#13]
Hello,
When I tried to publish an app with Maui.Nuke and got an error from Apple.
_ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/Nuke.framework/Nuke' contains bitcode._
There is [workaround](https://github.com/dotnet/maui/issues/10989#issuecomment-1304317816) for urgent cases but all libs built with XCode 14 should go with disabled Bitcode

**Comment by Cheesebaron** [comment]
![Screenshot 2023-01-02 at 08 55 10](https://user-images.githubusercontent.com/249719/210205805-8d67a874-b483-46a6-a0e4-31924d12fda0.png)

It is a bit weird as it is set to disabled.

Will look into this.

**Comment by Cheesebaron** [comment]
Can I get you to try the 2.0.13 version on NuGet?

**Comment by yurkinh** [comment]
Sure. Will try tomorrow in the morning

**Comment by Cheesebaron** [comment]
Seems like it is still an issue. I might need to tell Carthage to build Nuke without bitcode, will have another stab at this.

**Comment by yurkinh** [comment]
Well, with the updated nuget I was able to upload it to Test Flight and did not get any warnings like it was previously

**Comment by Cheesebaron** [comment]
Interesting. I got one, but perhaps I need to do more on my end then.

**Comment by Cheesebaron** [comment]
OK, I was pulling the old version of the package. Got a an App through to test flight now as well. Enjoy! Thanks for reporting!
