### ISSUE TITLE
Is it possible to add a placeholder?

### ISSUE THREAD

**Issue by KazysNoobiys** [roubachof/NukeProxy#5]
I would like to use Xamarin.Forms.Nuke, but I need support for adding a placeholder when loading an image. Is it possible to change the api to allow this? Something like this:

```
ImagePipeline.Shared.LoadImageWithUrl(
                new NSUrl("https://placekitten.com/g/300/300"),
                UIImage.FromBundle("Placeholder"),
                UIImage.FromBundle("ErrorPlaceholder"),
                (img, url) => image.Image = img);
```

**Comment by Cheesebaron** [comment]
Wrong repo. You should ask this here: https://github.com/roubachof/Xamarin.Forms.Nuke

**Comment by KazysNoobiys** [comment]
Perhaps. But without changes in the api nothing will work anyway.

**Comment by Cheesebaron** [comment]
The API already supports placeholders.

https://github.com/roubachof/NukeProxy/blob/master/NukeProxy/NukeProxy.swift#L42

**Comment by KazysNoobiys** [comment]
Yes, but it is not compatible with Xamarin.Forms.Nuke

**Comment by Cheesebaron** [comment]
I don't understand why this library that is just serving navtive UIKit should be "compatible" with framework X. It should be the other way around. Locking conversation here, it is off topic and makes no sense.
