### ISSUE TITLE
NuGet API key does not allow uploading new package

### ISSUE THREAD

**Issue by Cheesebaron** [roubachof/NukeProxy#9]
We've switched the package ID to ImageCaching.Nuke and uploads of new packages now fail.

@roubachof can you please update the API key so we can make a release of the new package? 

See failed run: https://github.com/roubachof/NukeProxy/actions/runs/3135176883/jobs/5090557484#step:4:52

```
Pushing ImageCaching.Nuke.2.0.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Forbidden https://www.nuget.org/api/v2/package/ 1668ms
error: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).
```

**Comment by roubachof** [comment]
I created a new key with the following glob:  ImageCaching.*

**Comment by Cheesebaron** [comment]
Thanks, works now :) https://www.nuget.org/packages/ImageCaching.Nuke
